server:
  port: ${PORT:8082}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}

spring:
  application:
    name: ${APP_NAME:ms-library-searcher}
  datasource:
    url: ${datasource_url}
    driver-class-name: org.postgresql.Driver
    username: ${datasource_username}
    password: ${datasource_password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    # defer-datasource-initialization: true